import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FiSearch, FiArrowRight } from 'react-icons/fi';
import LocationSelector from '../components/LocationSelector';
import RestaurantCard from '../components/RestaurantCard';
import FoodCard from '../components/FoodCard';
import { catalogApi } from '../services/api';
import './home.css';
export default function Home() {
  const [query, setQuery] = useState(''); const [restaurants, setRestaurants] = useState([]); const [foods, setFoods] = useState([]); const [categories, setCategories] = useState([]); const [error, setError] = useState(''); const navigate = useNavigate();
  useEffect(() => { Promise.all([catalogApi.restaurants(), catalogApi.foods(), catalogApi.categories()]).then(([r, f, c]) => { setRestaurants(r); setFoods(f); setCategories(c); }).catch((err) => setError(err.message)); }, []);
  const popular = useMemo(() => [...restaurants].sort((a, b) => b.rating - a.rating).slice(0, 4), [restaurants]); const popularFoods = foods.slice(0, 4);
  return <div className="page"><section className="hero"><div className="container hero-inner"><div className="hero-copy"><span className="page-header eyebrow">Campus Delivery, Reimagined</span><h1>Delicious Food, Delivered to You</h1><p className="hero-sub">Discover nearby restaurants and order your favorite meals.</p><form className="hero-search" onSubmit={(e) => { e.preventDefault(); navigate(`/restaurants${query ? `?q=${encodeURIComponent(query)}` : ''}`); }}><div className="hero-search-loc"><LocationSelector compact /></div><div className="hero-search-input"><FiSearch /><input placeholder="Search for food or restaurants..." value={query} onChange={(e) => setQuery(e.target.value)} /></div><button type="submit" className="btn btn-primary">Explore Restaurants <FiArrowRight /></button></form></div><div className="hero-visual" aria-hidden="true"><div className="hero-plate hero-plate-1"><img src="https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=500&q=60" alt="" /></div><div className="hero-plate hero-plate-2"><img src="https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=500&q=60" alt="" /></div></div></div></section><div className="container">{error && <div className="state-block"><h3>Could not load restaurants</h3><p className="muted">{error}</p></div>}<section className="section-block"><div className="section-head"><h2>Food Categories</h2></div><div className="category-row">{categories.filter((c) => c.id !== 'all').map((c) => <button key={c.id} className="category-chip" onClick={() => navigate(`/restaurants?category=${c.id}`)}>{c.name}</button>)}</div></section><section className="section-block"><div className="section-head"><h2>Popular Restaurants</h2><span className="link" onClick={() => navigate('/restaurants')} role="button">See all</span></div><div className="grid">{popular.map((r) => <RestaurantCard key={r.id} restaurant={r} />)}</div></section><section className="section-block"><div className="section-head"><h2>Nearby Restaurants</h2><span className="link" onClick={() => navigate('/restaurants')} role="button">See all</span></div><div className="grid">{restaurants.slice(0, 4).map((r) => <RestaurantCard key={r.id} restaurant={r} />)}</div></section><section className="section-block"><div className="section-head"><h2>Popular Foods</h2></div><div className="grid">{popularFoods.map((f) => <FoodCard key={f.id} food={f} showRestaurant />)}</div></section></div></div>;
}
