import db from '../config/db.js';

export async function listCustomers(req, res) {
  const [rows] = await db.execute('SELECT u.id, u.full_name, u.email, u.phone, u.is_active, u.created_at, COUNT(o.id) AS order_count FROM users u JOIN customers c ON c.user_id = u.id LEFT JOIN orders o ON o.customer_id = u.id GROUP BY u.id ORDER BY u.created_at DESC');
  res.json(rows);
}
export async function listRestaurants(req, res) { const [rows] = await db.execute('SELECT r.*, u.full_name AS owner_name, u.email AS owner_email FROM restaurants r JOIN users u ON u.id = r.owner_user_id ORDER BY r.created_at DESC'); res.json(rows); }
export async function listRiders(req, res) { const [rows] = await db.execute('SELECT dr.*, u.full_name, u.email, u.phone FROM delivery_riders dr JOIN users u ON u.id = dr.user_id ORDER BY u.created_at DESC'); res.json(rows); }
export async function listOrders(req, res) { const [rows] = await db.execute('SELECT o.*, r.name AS restaurant_name, u.full_name AS customer_name FROM orders o JOIN restaurants r ON r.id = o.restaurant_id JOIN users u ON u.id = o.customer_id ORDER BY o.placed_at DESC'); res.json(rows); }
export async function setCustomerStatus(req, res) { const { isActive } = req.body; if (typeof isActive !== 'boolean') return res.status(400).json({ message: 'isActive must be boolean' }); const [result] = await db.execute('UPDATE users u JOIN customers c ON c.user_id = u.id SET u.is_active = ? WHERE u.id = ?', [isActive, req.params.userId]); if (!result.affectedRows) return res.status(404).json({ message: 'Customer not found' }); res.json({ message: 'Customer status updated' }); }
export async function setRestaurantStatus(req, res) { const { status } = req.body; if (!['approved', 'rejected', 'blocked'].includes(status)) return res.status(400).json({ message: 'Invalid restaurant status' }); const [result] = await db.execute('UPDATE restaurants SET status = ? WHERE id = ?', [status, req.params.restaurantId]); if (!result.affectedRows) return res.status(404).json({ message: 'Restaurant not found' }); res.json({ message: 'Restaurant status updated' }); }
export async function setRiderStatus(req, res) { const { approvalStatus, isBlocked } = req.body; if (approvalStatus && !['pending', 'approved', 'rejected'].includes(approvalStatus)) return res.status(400).json({ message: 'Invalid rider approval status' }); if (isBlocked !== undefined && typeof isBlocked !== 'boolean') return res.status(400).json({ message: 'isBlocked must be boolean' }); const fields = []; const values = []; if (approvalStatus) { fields.push('approval_status = ?'); values.push(approvalStatus); } if (isBlocked !== undefined) { fields.push('is_blocked = ?'); values.push(isBlocked); } if (!fields.length) return res.status(400).json({ message: 'No status update provided' }); values.push(req.params.userId); const [result] = await db.execute(`UPDATE delivery_riders SET ${fields.join(', ')} WHERE user_id = ?`, values); if (!result.affectedRows) return res.status(404).json({ message: 'Rider not found' }); res.json({ message: 'Rider status updated' }); }
export async function assignRider(req, res) { const { riderId } = req.body; const [riders] = await db.execute('SELECT user_id FROM delivery_riders WHERE user_id = ? AND approval_status = \'approved\' AND is_blocked = FALSE', [riderId]); if (!riders[0]) return res.status(400).json({ message: 'Choose an approved rider' }); const [result] = await db.execute('UPDATE orders SET rider_id = ?, rider_status = \'assigned\' WHERE id = ? AND status = \'ready\' AND rider_id IS NULL', [riderId, req.params.orderId]); if (!result.affectedRows) return res.status(409).json({ message: 'Order cannot be assigned' }); await db.execute('INSERT INTO order_status_history (order_id, status, actor_user_id, note) VALUES (?, \'rider_assigned\', ?, ?)', [req.params.orderId, req.user.id, `Assigned to rider ${riderId}`]); res.json({ message: 'Rider assigned' }); }
